apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wasabi-deployment
  labels:
    app: wasabi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wasabi
  template:
    metadata:
      labels:
        app: wasabi
    spec:
      containers:
        - name: wasabi-main
          image: markmarine/wasabi-main:latest
          ports:
          - name: http
            containerPort: 8080
          - name: jmx
            containerPort: 8090
          - name: debug
            containerPort: 8180
          volumeMounts:
            - name: wasabi-config-vol
              mountPath: /etc/config
          env:
            - name: WASABI_CONF_DIR
              value: /etc/config
      volumes:
        - name: wasabi-config-vol
          configMap:
            name: wasabi-conf-dev

